# -*- coding: utf-8 -*-
"""Average_calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dbPEJVl7_FmnKJNcuYEI7keaaSHtCUur
"""

#create a function that can calculate the average
def average_calculator(marks):
    sum_of_marks = sum(marks)
    length_of_marks = len(marks)
    result = sum_of_marks / length_of_marks
    return result

marks_input = input("input marks hier (comma separated): \n")
marks_list = [int(mark) for mark in marks_input.split(",")]

result = average_calculator(marks_list)
print("your average is:", result)